=== DataArt-Latona/latona-datacatalog/src/addonInternals/latona-datacatalog-options-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "definitions": {
    "nonEmptyString": {
      "type": "string",
      "minLength": 1
    },
    "properties": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "$ref": "#/definitions/nonEmptyString" },
          "path": { "$ref": "#/definitions/nonEmptyString" },
          "title": { "$ref": "#/definitions/nonEmptyString" },
          "show": { "type": "boolean" },
          "showInLinkTable": { "type": "boolean" }
        },
        "required": ["name", "path", "title"],
        "additionalProperties": false
      }
    },
    "detailsCollection": {
      "type": "object",
      "properties": {
        "collection": { "$ref": "#/definitions/nonEmptyString" },
        "properties": { "$ref": "#/definitions/properties" },
        "heading": { "$ref": "#/definitions/nonEmptyString" }
      },
      "required": ["collection", "properties", "heading"],
      "additionalProperties": false
    },
    "sectionDefinition": {
      "type": "object",
      "properties": {
        "properties": { "$ref": "#/definitions/properties" },
        "inParentAs": {
          "type": "string",
          "enum": ["linkTable", "linkList", "section"]
        },
        "tableLinkProperty": { "$ref": "#/definitions/nonEmptyString" },
        "titleTemplate": { "$ref": "#/definitions/nonEmptyString" },
        "slugTemplate": { "$ref": "#/definitions/nonEmptyString" }
      },
      "required": ["properties", "inParentAs", "titleTemplate", "slugTemplate"],
      "additionalProperties": false
    },
    "sectionBy": {
      "type": "object",
      "properties": {
        "first": { "$ref": "#/definitions/sectionDefinition" },
        "second": { "$ref": "#/definitions/sectionDefinition" }
      },
      "required": ["first"],
      "additionalProperties": false
    },
    "catalog": {
      "type": "object",
      "properties": {
        "collection": { "$ref": "#/definitions/nonEmptyString" },
        "title": { "$ref": "#/definitions/nonEmptyString" },
        "slug": { "$ref": "#/definitions/nonEmptyString" },
        "sectionBy": { "$ref": "#/definitions/sectionBy" },
        "details": { "$ref": "#/definitions/sectionDefinition" },
        "detailsCollections": {
          "patternProperties": {
            "^[a-zA-Z]+$": { "$ref": "#/definitions/detailsCollection" }
          },
          "additionalProperties": false
        }
      },
      "required": ["collection", "title", "slug", "details"],
      "additionalProperties": false
    },
    "catalogCollection": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z]+$": {
          "$ref": "#/definitions/catalog"
        }
      },
      "additionalProperties": false
    }
  },
  "type": "object",
  "properties": {
    "paths": {
      "type": "object",
      "properties": {
        "outPath": { "$ref": "#/definitions/nonEmptyString" },
        "customContentPath": { "$ref": "#/definitions/nonEmptyString" }
      },
      "required": ["outPath"],
      "additionalProperties": false
    },
    "renderFormat": { "type": "string", "enum": ["md", "html", "conf"] },
    "pageTreeFileName": { "$ref": "#/definitions/nonEmptyString" },
    "conf": {
      "type": "object",
      "properties": {
        "createNotesPage": { "type": "boolean" },
        "notesSlugSuffix": { "$ref": "#/definitions/nonEmptyString" },
        "notesTitleSuffix": { "$ref": "#/definitions/nonEmptyString" },
        "modelConfig": {
          "spaceKey": { "type": "string" }
        }
      },
      "required": ["createNotesPage", "notesSlugSuffix", "notesTitleSuffix"],
      "additionalProperties": false
    },
    "relationshipsCollection": { "$ref": "#/definitions/nonEmptyString" },
    "relationshipTypesCollection": { "$ref": "#/definitions/nonEmptyString" },
    "catalogs": {
      "$ref": "#/definitions/catalogCollection"
    },
    "dropDefaultCatalogs": { "type": "boolean" }
  },
  "required": [
    "paths",
    "renderFormat",
    "pageTreeFileName",
    "catalogs",
    "relationshipsCollection",
    "relationshipTypesCollection"
  ],
  "additionalProperties": false
}

=== DataArt-Latona/latona-datacatalog/test/mocks/validators.spec/testOptions.json
{
  "paths": {
    "outPath": "./output",
    "customContentPath": "./content"
  },
  "renderFormat": "md",
  "pageTreeFileName": "___page_tree___.json",
  "conf": {
    "createNotesPage": true,
    "notesSlugSuffix": "-notes",
    "notesTitleSuffix": " - Notes"
  },
  "catalogs": {
    "dataCatalog": {
      "collection": "tables",
      "title": "Data catalog",
      "slug": ".datacatalog",
      "sectionBy": {
        "first": {
          "properties": [
            { "name": "db", "path": "db", "title": "Database", "show": false },
            {
              "name": "tableCount",
              "path": "$length",
              "title": "Table count",
              "show": false
            }
          ],
          "inParentAs": "linkList",
          "tableLinkProperty": "db",
          "titleTemplate": "Database - ${db}",
          "slugTemplate": "db-[${db}]"
        },
        "second": {
          "properties": [
            {
              "name": "db",
              "path": "db",
              "title": "Database",
              "show": true,
              "showInLinkTable": true
            },
            {
              "name": "schema",
              "path": "schema",
              "title": "Schema",
              "show": true,
              "showInLinkTable": true
            },
            {
              "name": "tableCount",
              "path": "$length",
              "title": "Table count",
              "show": true,
              "showInLinkTable": true
            }
          ],
          "inParentAs": "linkTable",
          "tableLinkProperty": "schema",
          "titleTemplate": "Schema - [${db}].[${schema}]",
          "slugTemplate": "sc-[${db}].[${schema}"
        }
      },
      "details": {
        "properties": [
          {
            "name": "db",
            "path": "db",
            "title": "Database",
            "show": false,
            "showInLinkTable": false
          },
          {
            "name": "schema",
            "path": "schema",
            "title": "Schema",
            "show": true,
            "showInLinkTable": true
          },
          {
            "name": "tableName",
            "path": "tableName",
            "title": "Table name",
            "show": true,
            "showInLinkTable": true
          },
          {
            "name": "fieldCount",
            "path": "fields.length",
            "title": "Field count",
            "show": true,
            "showInLinkTable": true
          }
        ],
        "inParentAs": "section",
        "tableLinkProperty": "tableName",
        "titleTemplate": "Table - [${db}].[${schema}].[${tableName}]",
        "slugTemplate": "tbl-[${db}].[${schema}].[${tableName}]"
      },
      "detailsCollections": {
        "someCollection": {
          "collection": "fields",
          "properties": [
            { "name": "fieldName", "path": "fieldName", "title": "Field name" },
            { "name": "sqlType", "path": "sqlType", "title": "SQL Type" }
          ],
          "heading": "Fields"
        }
      }
    }
  },
  "relationshipsCollection": "relationships",
  "relationshipTypesCollection": "relationshipTypes"
}

=== DataArt-Latona/latona-datacatalog/src/addonInternals/latona-datacatalog-options-defaults.json
{
  "paths": {
    "outPath": "./output",
    "customContentPath": "./content"
  },
  "renderFormat": "md",
  "pageTreeFileName": "___page_tree___.json",
  "conf": {
    "createNotesPage": true,
    "notesSlugSuffix": "-notes",
    "notesTitleSuffix": " - Notes",
    "modelConfig": {
      "spaceKey": "TEST"
    }
  },
  "catalogs": {
    "dataCatalog": {
      "collection": "tables",
      "title": "Data catalog",
      "slug": ".datacatalog",
      "sectionBy": {
        "first": {
          "properties": [
            { "name": "db", "path": "db", "title": "Database", "show": false }
          ],
          "inParentAs": "linkList",
          "tableLinkProperty": "db",
          "titleTemplate": "Database - ${db}",
          "slugTemplate": "db-[${db}]"
        },
        "second": {
          "properties": [
            {
              "name": "db",
              "path": "db",
              "title": "Database",
              "show": true,
              "showInLinkTable": true
            },
            {
              "name": "schema",
              "path": "schema",
              "title": "Schema",
              "show": true,
              "showInLinkTable": true
            },
            {
              "name": "tableCount",
              "path": "$items.length",
              "title": "Table count",
              "show": true,
              "showInLinkTable": true
            }
          ],
          "inParentAs": "section",
          "tableLinkProperty": "schema",
          "titleTemplate": "Schema - [${db}].[${schema}]",
          "slugTemplate": "sc-[${db}].[${schema}]"
        }
      },
      "details": {
        "properties": [
          {
            "name": "db",
            "path": "db",
            "title": "Database",
            "show": false,
            "showInLinkTable": false
          },
          {
            "name": "schema",
            "path": "schema",
            "title": "Schema",
            "show": true,
            "showInLinkTable": true
          },
          {
            "name": "tableName",
            "path": "tableName",
            "title": "Table name",
            "show": true,
            "showInLinkTable": true
          },
          {
            "name": "fieldCount",
            "path": "fields.length",
            "title": "Field count",
            "show": true,
            "showInLinkTable": true
          }
        ],
        "inParentAs": "linkTable",
        "tableLinkProperty": "tableName",
        "titleTemplate": "Table - [${db}].[${schema}].[${tableName}]",
        "slugTemplate": "[${db}].[${schema}].[${tableName}]"
      },
      "detailsCollections": {
        "fields": {
          "collection": "fields",
          "properties": [
            { "name": "fieldName", "path": "fieldName", "title": "Field name" },
            { "name": "sqlType", "path": "sqlType", "title": "SQL Type" }
          ],
          "heading": "Fields"
        }
      }
    },
    "businessProcessCatalog": {
      "collection": "collections.businessProcesses",
      "title": "Business processes catalog",
      "slug": ".bpcatalog",
      "sectionBy": {
        "first": {
          "properties": [
            {
              "name": "group",
              "path": "group",
              "title": "Group",
              "show": false,
              "showInLinkTable": false
            }
          ],
          "inParentAs": "section",
          "tableLinkProperty": "group",
          "titleTemplate": "Process group - ${group}",
          "slugTemplate": "bpgroup-${group}"
        }
      },
      "details": {
        "properties": [
          {
            "name": "group",
            "path": "group",
            "title": "Group",
            "show": true,
            "showInLinkTable": true
          },
          {
            "name": "title",
            "path": "title",
            "title": "Name",
            "show": true,
            "showInLinkTable": true
          }
        ],
        "inParentAs": "linkTable",
        "tableLinkProperty": "title",
        "titleTemplate": "Process - ${title}",
        "slugTemplate": "${id}"
      }
    },
    "applicationsCatalog": {
      "collection": "collections.applications",
      "title": "Applications catalog",
      "slug": ".appcatalog",
      "sectionBy": {
        "first": {
          "properties": [
            {
              "name": "group",
              "path": "group",
              "title": "Group",
              "show": false,
              "showInLinkTable": false
            }
          ],
          "inParentAs": "section",
          "tableLinkProperty": "group",
          "titleTemplate": "App group - ${group}",
          "slugTemplate": "appgroup-${group}"
        }
      },
      "details": {
        "properties": [
          {
            "name": "group",
            "path": "group",
            "title": "Group",
            "show": true,
            "showInLinkTable": true
          },
          {
            "name": "title",
            "path": "title",
            "title": "Name",
            "show": true,
            "showInLinkTable": true
          }
        ],
        "inParentAs": "linkTable",
        "tableLinkProperty": "title",
        "titleTemplate": "App - ${title}",
        "slugTemplate": "${id}"
      }
    }
  },
  "relationshipsCollection": "relationships",
  "relationshipTypesCollection": "relationshipTypes"
}
